name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup pnpm
        uses: pnpm/action-setup@v5
      - name: setup node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24
      - name: install deps and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
      - name: copy necessary files
        run: |
          cp package.json dist/
          cp config.jsonc dist/
          cp locales/* dist/
      - name: archive artifacts
        run: |
          zip -r bot-server_${{ github.ref_name }}.zip dist
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: bot-server_${{ github.ref_name }}.zip
